/* This is autogenerated code. */

/* (generated Sat, 22 Oct 2016 14:18:58 +0200 by ladder-gen v 1.0) */

#ifndef LADDER_H
#define LADDER_H

#if ARDUINO >= 100
    #include "Arduino.h"   
#else
    #include "WProgram.h"
#endif

#define BOOL boolean
#define SWORD int

#define EXTERN_EVERYTHING
#define NO_PROTOTYPES

void PlcCycle(void);

/* Configure digital I/O according to LD (call this in setup()). */

inline void PlcSetup()
{
	pinMode(12, INPUT);
	pinMode(13, OUTPUT);
}


/* Individual pins (this code is used in ladder.cpp) */

inline extern BOOL Read_U_b_XButton(void)
{
    // TODO
	return digitalRead(12);
	
}

inline BOOL Read_U_b_YLED(void)
{
    // TODO
	return digitalRead(13);
}

inline void Write_U_b_YLED(BOOL v)
{
    // TODO
	digitalRead(13,v);
}


#endif